name: Master Branch Release

on:
  push:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  docker-release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Checkout Repository
        uses: actions/checkout@v4
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            beanbeanjuice/reddit-maker-bot:latest
          provenance: true
          sbom: true
